version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /home/ec2-user/foo/deploy_hooks
    mode: 755
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user